<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class CompanyBif extends Model
{
    protected $fillable = [
        'company_id',
        'title',
        'bif_no',
        'bif_date',
        'client_type',
        'business_organization',
        'business_organization_other',
        'nationality_status',
        'office_type',
        'office_type_other',
        'business_name',
        'alternative_business_name',
        'business_address',
        'zip_code',
        'business_phone',
        'mobile_no',
        'tin_no',
        'place_of_incorporation',
        'date_of_incorporation',
        'industry_services',
        'industry_export_import',
        'industry_education',
        'industry_financial_services',
        'industry_transportation',
        'industry_distribution',
        'industry_manufacturing',
        'industry_government',
        'industry_wholesale_retail_trade',
        'industry_other',
        'industry_other_text',
        'capital_micro',
        'capital_small',
        'capital_medium',
        'capital_large',
        'employee_male',
        'employee_female',
        'employee_pwd',
        'employee_total',
        'source_revenue_income',
        'source_investments',
        'source_remittance',
        'source_other',
        'source_other_text',
        'source_fees',
        'president_name',
        'treasurer_name',
        'authorized_signatory_name',
        'authorized_signatory_address',
        'authorized_signatory_nationality',
        'authorized_signatory_date_of_birth',
        'authorized_signatory_tin',
        'authorized_signatory_position',
        'ubo_name',
        'ubo_address',
        'ubo_nationality',
        'ubo_date_of_birth',
        'ubo_tin',
        'ubo_position',
        'authorized_contact_person_name',
        'authorized_contact_person_position',
        'authorized_contact_person_email',
        'authorized_contact_person_phone',
        'signature_printed_name',
        'signature_position',
        'review_signature_printed_name',
        'review_signature_position',
        'sales_marketing_name',
        'sales_marketing_date_signature',
        'finance_name',
        'finance_date_signature',
        'referred_by',
        'consultant_lead',
        'lead_associate',
        'president_use_only_name',
        'status',
        'submitted_at',
        'approved_at',
        'approved_by_name',
        'rejected_at',
        'rejected_by_name',
        'rejection_reason',
        'created_by',
        'updated_by',
    ];

    protected $casts = [
        'bif_date' => 'date',
        'date_of_incorporation' => 'date',
        'industry_services' => 'boolean',
        'industry_export_import' => 'boolean',
        'industry_education' => 'boolean',
        'industry_financial_services' => 'boolean',
        'industry_transportation' => 'boolean',
        'industry_distribution' => 'boolean',
        'industry_manufacturing' => 'boolean',
        'industry_government' => 'boolean',
        'industry_wholesale_retail_trade' => 'boolean',
        'industry_other' => 'boolean',
        'capital_micro' => 'boolean',
        'capital_small' => 'boolean',
        'capital_medium' => 'boolean',
        'capital_large' => 'boolean',
        'source_revenue_income' => 'boolean',
        'source_investments' => 'boolean',
        'source_remittance' => 'boolean',
        'source_other' => 'boolean',
        'source_fees' => 'boolean',
        'authorized_signatory_date_of_birth' => 'date',
        'ubo_date_of_birth' => 'date',
        'submitted_at' => 'datetime',
        'approved_at' => 'datetime',
        'rejected_at' => 'datetime',
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }
}
